### ISSUE TITLE
PRACTICA 5

### ISSUE THREAD

**Issue by HECTOR-KDM02** [SistemasTecTlaxiaco/actividad-5-proceso-de-negocio-en-bizagi-con-web-30-equipo-osteas-b#1]
[Practica 5.pdf](https://github.com/user-attachments/files/17120283/Practica.5.pdf)

Reporte Practica 5

**Comment by ArcangelGC** [comment]
En base a todo lo checado otorgamos una calificación de 20/20 en base a la rúbrica. 
Recomendaciones el interlineado pero de ahí en fuera todo está bien.

**Comment by josealfredo79** [comment]
@HECTOR-KDM02 Favor de integrar el proceso de negocio

**Comment by HECTOR-KDM02** [comment]
[Practica 5-1.pdf](https://github.com/user-attachments/files/17156485/Practica.5-1.pdf)

**Comment by josealfredo79** [comment]
@HECTOR-KDM02 Las entidades siempre son las personas, sistemas y que interactuan con las actividades del proceso.favor checar para la proxima practica..
